### Get List of Items that could be granted to players
GET http://localhost:8080/api/actions/log
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTI3NjY2NzUsImV4cCI6MTcxMjc3MDI3NSwicm9sZXMiOlsiUk9MRV9FRElUT1IiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJlZGl0b3IifQ.nUN7n6bLizWVylM5QQrM9UA1SGQz-_JbfmzUHBuF_yUEMPseR4TMweNdFieddWKnCVQPVx4B3aihsXlPRzcqky9H2eio70Pqcv6yZN_dGhm4Igc5Wzf5GOMk8Sx63Lu5qp-V1HAvRm0isYEGt2VRtSgcIorGIe9fbUBlsiVOac3TGJmg_7Bn2wiwmDwDTdCCNaO8JwBlYOGms3XAxpvPjxoApQ4OytL-3HORSiZUoUCNnue62xUMItLsUStoUI7z0RRxS4Gz6JZtFbvpFsQq0W2cJYb7X8WeoCAWmjMiG0Dejy2ioNqA_T1NEfJeMQ0C4ngCO67kuZduY2uWnZZhmce4ORGFD7rcoKXRn-yCs7D-1QYat9gVXyZVctTOvsI5hog5QdNOCj_opxYDx3gkVUL-LUApq1TCbCRxtjIiTFnnK3ZtrmgqopCJqJxMGu2JwYqBTrhPzgx7xJkffJXYiKU23BTaJyN-e1-h2qkQkuRUPP7pBoYYs-gCYtxnY5_pc72qCVRFHfndNoUinRWGMVLwSm5jh2JS1tHrs3w0L1sUFyM9z8zdXt4yZCOrv4wiA8KyXSLcqhFAbOTbzD8FVBBBtjx9HEbpNi1AkPirmhalwXaecJz_nmd-LaBz4RgfxDqOTPEjn8orm0QROCoWgJxNnK04ekPuCldiqsdALtI