### Get List of Items that could be granted to players
GET http://localhost:8080/api/items
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTI2NjM3MDcsImV4cCI6MTcxMjY2NzMwNywicm9sZXMiOlsiUk9MRV9FRElUT1IiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJlZGl0b3IifQ.TZIw_YVgH1LtKeiaZjKyrJKzSEcmVBt4YeoioK_0e4CRV7egZ-3JsLq_q82xmtBwTTbjsFaLHdTW4FUu196Aw0cnVP2nsp6rvfFj3HreYcc7zXkfWjYy3rxYwbSck1-q7zgz6iMIcD6C3o1p4LlaeOWw3qZbN8ssoHM8TRcZE5Ki7NI4jFQnxuLqG8G34tIa7zmq5BUplUlv-BqUDgr8FF0GK0_r4gXfgKKVBKX_NTuDU-o58TX8EFyn-qb8w3WsYGU9-1jcXp5bJfpUxcfmp0NRFS95RDTC5Tnv61iWgZCutilbeF6_Xxf3nurx-_6-KJJAVLWJk_9ai7Tj4mm_88lIYBPH4oEkLodDSy-B0gsqSP4zKBlVWSVKbkA0z3GO73IMWtLVcc7MWCiKaRemh9nTRxUaf3fSNPrWFZTNRvvSZeyJs5qmQCwN7RPsEXf7bHPSWU9TX-ah1CCQZGEsN0IMo3RxoBEvWqMCfmRdAKroqLUYU7kMhX53AyujCytC42uctfzyosM_q5m4KYrLhQI66Dlr6J7fDGwkpFVyPwrzmQgTK6SRvrVrkLiUCtBJ1Lnz1TintmtgTdkcFm2Rh-TimdhFK3dhpYAm_IvJp3GhF6vVdgpZcy9og67q0SYDGojpA662T4Gsnbeae7RWNDWWojncF587A6olwXE-5Ho