POST http://localhost:8080/api/item-grants
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTI4MzgwNzQsImV4cCI6MTcxMjkyNDQ3NCwicm9sZXMiOlsiUk9MRV9FRElUT1IiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJlZGl0b3IifQ.ZK1LHODLufU6SvccYMH3ZmAMIo4kjIFLy1npJATCnPOuBiYi-o8hAiYn5WmGoNA9_KMI35U9RI6oWAOlSbucPsi5YYlhijjF7o7XCKxQ5a4SfmwzxZ-zyB8o6ItOiOwZZs4DrgReEppSE4Lp3URGTvcYXVQ5xHTPny-8Caya5u_SEAmi74Igtl8nBGtCz_qHmER6HIs3WDylYdwcrE9F5KEOIjbvsrm5Zq_gIv2JT05l3URNJf2AptInfbVpoh1htZd3U0ayWrLt4rbiVHtzyO-v50PdVNyWItbGTYtcwTVOW2Ts3aJkz6435YRFA7wNotH3A-DjfcJfVthSXdenH6tLx7i2RMSmPXFQjjdFFb8IqFR_z-JVwsoMsVgPIDyuhJ_uUlvb379TXDU6US1pJFOZ200UR1xDvwj_aaktG2ACjHGlJ7Tgb9E9z4NLnG5CaOk59Ro39n9d1-57VqPlwqXv63mwdraO_31KWDZLSXGFin3jRW3ZqLFF_WFlB1HwX03PZ8DGJlHvmwwp9WHzOvQxMkBxYteV2doByPLiShgkMGqwXsgLY0sITuSDT2Dg7eFmGGR6I3164X7eRjTEDmbfeirJUT0wb04wsl-2a0sJOGjYnTYP6TVNZfPpCoQFP0jOd3-S5XkjpCLlKmyNePanAgRI4tl6pH5DifeSFLk

{
  "playerId": 1,
  "items": [1,2]
}
