POST http://localhost:8080/api/player-messages
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTI4Mjg2ODYsImV4cCI6MTcxMjgzMjI4Niwicm9sZXMiOlsiUk9MRV9FRElUT1IiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJlZGl0b3IifQ.n7p8HQD4B8-nFglqA5TZwb3C6GjwbCwlwcfYaYTcu_w3zroZc2iRuJkUbiIQyH63XW3WTDffrqBwvdlNfCbG74DdT-w7W7cfMijd87HKX9nQ36CPNIoIqjDOfExR8Ec8daV6uS7PlUXQzq7-SugIi-gthGiOnFTyYO5f6mOWm69nWCCZKOCF0TimJMQ30W270r1bhT1IRcUsl3tVVpFrnlBAA899YB6jDvL709nP0ZhPEnMupk-krd4AsUAyD8m8B64Wd34G1VGaAIAvMfHMGKE53aQl_TqrS2DD3BpxDLkWXOlk8MpIlShv6qsvfVzmfZZ6C4A6BjO-CXq2t6QW8QSOpecTMOV5FD2WM29pWCptn2BqoeLzdzXKapBvF0DpxFGcnFCQLmgfAj9zcQAZimZq0HHnJ3R2HtSo3YpZREtTt6Zc6CVPxC4SM67hdphGZuSwH9WCeWe0G_q2j6GZDDOS4WEwg_yAhkzpOGn-jeehFSLuCJrx-rTCf9gabtD2j497VmmknQL_VyW114Gt_vzhtTKCXplwFax0R3YDkISV2hzmqiffnFYKflefsEiXpgpb5m8r7o-ZgIJ_55uEQuG0HNaN0O9MqX0idUt4yt22dqch8iUY_Xmwiy66DG5YoxaWxlMyKkNe6LkHmlNLxkvSD0fZreQteddK74RIx5I

{
  "playerId": 1,
  "message": "Test message"
}
